/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $u: typeof import('uview-pro').$u
  const EffectScope: typeof import('vue').EffectScope
  const appBaseUrl: typeof import('@/env').appBaseUrl
  const baseUrl: typeof import('@/env').baseUrl
  const commonApi: typeof import('@/api').commonApi
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const currentEnv: typeof import('@/env').currentEnv
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const env: typeof import('@/env').env
  const envConfig: typeof import('@/env').envConfig
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const navigateBack: typeof import('@/utils/router').navigateBack
  const navigateTo: typeof import('@/utils/router').navigateTo
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onHide: typeof import('@dcloudio/uni-app').onHide
  const onLoad: typeof import('@dcloudio/uni-app').onLoad
  const onMounted: typeof import('vue').onMounted
  const onPageScroll: typeof import('@dcloudio/uni-app').onPageScroll
  const onPullDownRefresh: typeof import('@dcloudio/uni-app').onPullDownRefresh
  const onReachBottom: typeof import('@dcloudio/uni-app').onReachBottom
  const onReady: typeof import('@dcloudio/uni-app').onReady
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onShareAppMessage: typeof import('@dcloudio/uni-app').onShareAppMessage
  const onShow: typeof import('@dcloudio/uni-app').onShow
  const onTabItemTap: typeof import('@dcloudio/uni-app').onTabItemTap
  const onUnload: typeof import('@dcloudio/uni-app').onUnload
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reLaunch: typeof import('@/utils/router').reLaunch
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const redirectTo: typeof import('@/utils/router').redirectTo
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const switchTab: typeof import('@/utils/router').switchTab
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const userApi: typeof import('@/api').userApi
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}
