admin:
  common:
    systemName: 后台管理系统
    emailForm: 1006059906@qq.com
    platformName: 奇点趣造
    upload:
      root: upload

mybatis-plus:
  # 配置slq打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baise_star_anise?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
#      password: abcsee2see



# 第三方登录配置
justauth:
  enabled: true
  type:
    wechatmini:
      clientId: wxb17c548aacf18210
      clientSecret: 432e40823eefc7dae4b518cf958943b6
      # 因为justauth会校验 redirectUri地址，不设置会报错
      redirectUri: https://5f73-183-240-211-140.ngrok-free.app
      unionId: true
